### ISSUE TITLE
Error when using the plugin, `Error: RangeError: options.port should be >= 0 and < 65536. Received type number (NaN).`

### ISSUE THREAD

**Issue by Jandev** [GillesZunino/insomnia-plugin-azure-ad-authentication#10] opened 2024-04-05 08:44 UTC
When using the plugin I'm facing an error stating:

> Error: RangeError: options.port should be >= 0 and < 65536. Received type number (NaN).

Disabling, or removing, the plugin solves the issue.

Because I couldn't install this plugin via the UI due to some npm-error, I cloned the repository in the plugins folder and built the plugin myself (tried both prod and dev builds).

Steps I have taken:

1. Navigate to the plugins folder
2. Perform a `git clone https://github.com/GillesZunino/insomnia-plugin-azure-ad-authentication.git`
3. `cd .\insomnia-plugin-azure-ad-authentication\`
4. Run `npm run build:prod`
5. Start Insomnia client
6. Reload all plugins (there's only this one)
7. Configure a request to use the plugin
![Screenshot of the configured plugin with blurred values](https://github.com/GillesZunino/insomnia-plugin-azure-ad-authentication/assets/462356/83bec118-78c6-4645-9d7f-343b0f995418)

8. Invoke it and see the error.

_I'm using the Postman callback URL over here because that one is already configured in our App Registration_

**Comment by GillesZunino** [comment] 2024-04-08 20:52
Re-using the Postman callback URL (https://oauth.pstmn.io/v1/callback or variants) for "Redirect URI" as show above is not currently supported.

We now reject these urls early in the configuration dialog. We also no longer fail with a cryptic exception. The documentation has been updated to indicate that any redirect url against *pstmn.io cannot be used.

I will produce a release in the next few days.

**Comment by Jandev** [comment] 2024-04-09 09:14
> Re-using the Postman callback URL (https://oauth.pstmn.io/v1/callback or variants) for "Redirect URI" as show above is not currently supported.
> 
> We now reject these urls early in the configuration dialog. We also no longer fail with a cryptic exception. The documentation has been updated to indicate that any redirect url against *pstmn.io cannot be used.
> 
> I will produce a release in the next few days.

Thanks!
I also noticed a similar error with other (public) URIs defined.

I now added both `http://localhost:1234/redirect` and `http://127.0.0.1:1234/redirect` to the configuration in the `Mobile and desktop applications`-section because of the `https`-validation for Web.

I'm now confronted with a message stating:

> Error: ClientAuthError: endpoints_resolution_error: Endpoints cannot be resolved

![Browser screenshot `Error: ClientAuthError: endpoints_resolution_error: Endpoints cannot be resolved`](https://github.com/GillesZunino/insomnia-plugin-azure-ad-authentication/assets/462356/31f48504-8415-4ba3-beaa-9b259389e453)

Still using the Code grant with PKCE flow.

Not sure if I need to configure Insomnia to 'listen' to this endpoint or not. Could be I'm overlooking a specific part on it in the docs.

**Comment by GillesZunino** [comment] 2024-04-10 16:46
Yes! It is still in dev, not yet released and not ready for consumption. The issue is not yet closed indicating this is till being worked on. Thank you.

**Closed as completed** 2024-04-11 00:25 UTC
